apiVersion: v1
kind: Service
metadata:
  name: ers-backend-svc
spec:
  selector:
    app: ers-backend
  ports:
    - name: backend
      port: 80
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ers-frontend-svc
spec:
  selector:
    app: ers-frontend
  ports:
    - port: 80
      targetPort: 5173
      protocol: TCP
