import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles/globals.css'
import './styles/theme.css'
import './styles/layout.css'
import './styles/cards.css'
import './styles/charts.css'
import './styles/dashboard.css'
import './styles/forms.css'
import './styles/insights.css'
import './styles/rollback.css'
import './styles/scoring.css'
import './styles/table.css'
import './styles/training.css'

createRoot(document.getElementById('root')).render(<App />)
